Exploring the CF Trust registry data from 2008 to 2018 data to evaluate if model output (synthesizing FEV1, FEF25-75 on 2 days) can be used to improve ML achieved from each indidivually

In [1]:
import logging

import pandas as pd

import data.helpers as dh
import models.var_builders as var_builders
import data.cfr_data_19_23 as cfrd
import data.breathe_data as bd
import cfr.cfr_viz_helpers as vh

In [ ]:
df = pd.read_csv(
    dh.get_path_to_main() + f"DataFiles/CFR/CF2018.csv",
    # usecols=['ID'],
    encoding="cp1252",
)
# 2008 hasn't FEF25-75

/var/folders/zq/v2r6yn111s3gpdf8lzf72xvw0000gn/T/ipykernel_9964/3928585658.py:1: DtypeWarning: Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [3]:
df.loc[df["ID"] == "B168895", "Intravenous (IV) Antibiotic Days in Hospital"] = 365

In [11]:
df["IV days"] = (
    df["Intravenous (IV) Antibiotic Days at Home"]
    + df["Intravenous (IV) Antibiotic Days in Hospital"]
)
df["IVs"] = (
    df["Intravenous (IV) Antibiotic Numbers at Home"]
    + df["Intravenous (IV) Antibiotic Numbers in Hospital"]
)

In [5]:
col_vis = [
    "ID",
    "Intravenous (IV) Antibiotic Days at Home",
    "Intravenous (IV) Antibiotic Days in Hospital",
    "Intravenous (IV) Antibiotic Numbers in Hospital",
    "Intravenous (IV) Antibiotic Numbers at Home",
    "IV days",
]

In [16]:
df[col_vis].isna().sum()

ID                                                  0
Intravenous (IV) Antibiotic Days at Home           13
Intravenous (IV) Antibiotic Days in Hospital        8
Intravenous (IV) Antibiotic Numbers in Hospital     3
Intravenous (IV) Antibiotic Numbers at Home         4
IV days                                            14
dtype: int64

In [7]:
df[col_vis].describe()

,Intravenous (IV) Antibiotic Days at Home,Intravenous (IV) Antibiotic Days in Hospital,Intravenous (IV) Antibiotic Numbers in Hospital,Intravenous (IV) Antibiotic Numbers at Home,IV days
count,9834.000000,9839.000000,9844.000000,9843.000000,9833.000000
mean,6.504169,9.619474,0.811967,0.529412,16.122140
std,17.434226,21.153851,1.455526,1.225957,29.581957
min,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.000000,13.000000,1.000000,0.000000,22.000000
max,340.000000,365.000000,16.000000,13.000000,445.000000

In [8]:
df[df["IV days"] > 360][col_vis]

,ID,Intravenous (IV) Antibiotic Days at Home,Intravenous (IV) Antibiotic Days in Hospital,Intravenous (IV) Antibiotic Numbers in Hospital,Intravenous (IV) Antibiotic Numbers at Home,IV days
2333,B163943,340.0,39.0,3.0,4.0,379.0
3197,B168895,0.0,365.0,1.0,0.0,365.0
4122,B160040,193.0,252.0,4.0,3.0,445.0

In [9]:
import plotly.express as px
import numpy as np

fig = vh.plot_IV_days_hist(df, 'IV days', False)
fig.show()

In [ ]:
# for year in [2008, 2009, 2010, 2011, 2012, 2013, 2014]:
for year in [2016, 2017, 2018]:
    print(year)
    df1 = pd.read_csv(
        dh.get_path_to_main() + f"DataFiles/CFR/CF{year}.csv",
        # usecols=['ID'],
        encoding="cp1252",
    )
    print(df1.columns.to_list())

2016

/var/folders/zq/v2r6yn111s3gpdf8lzf72xvw0000gn/T/ipykernel_45181/365697482.py:4: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.

/var/folders/zq/v2r6yn111s3gpdf8lzf72xvw0000gn/T/ipykernel_45181/365697482.py:4: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.

['ID', 'Gender', 'Genetic Mutation Allele 1', 'Genetic Mutation Allele 2', 's02genotypemut1specify', 's02genotypemut2specify', 'Height', 'Centile Height', 'Weight', 'Centile Weight', 'BMI', 's01encounterageyears', 's01encounteragemonths', 's03deathhaspatientdied', 's03deathcause', 'death_dt_anon', 'received_trans', 's10transplantdate', 'trans_lung_bilat', 'trans_lung_heart', 'trans_lung_lb_cadaveric', 's10transplantevaluation', 's10transplantevaluationoutcome', 's10transplantevaluationdate', 'FEV1', 'FEV1 Predicted', 'Best FEV1', 'Best FEV1 Predicted', 'smokeCigarettes', 'cmpl_diab_hgba1c_val', 'cmpl_hemoptysis', 'HemoptysisScanty', 'HemoptysisSevere', 'HemoptysisMassive', 'HemoptysisModerate', 'cmpl_CFRD', 'cmpl_diab_with_hyperglycemia', 'cmpl_other_glucose_ab', 'cfrd_treatment', 'cmpl_diab_gluc_intoler', 'cmpl_diab_dietary_chg', 'cmpl_oral_hypoglycemic_agnts', 'cmpl_diab_inter_insul', 'cmpl_microalbuminuria', 'cmpl_diabetes', 'cmpl_retinopathy', 'cmpl_cancer', 'cmpl_Arrhythmia', 'cmpl_Bradyarrythmia', 'cmpl_Tachyarrythmia', 'cmpl_Cough_Fracture', 'cmpl_Pulmonary_Abscess', 'cmpl_Cardiac_Disease', 'cmpl_Cardiac_Arrest', 'cmpl_Cardiomyopathy', 'cmpl_Congenital_heart_disease', 'cmpl_Heart_Failure', 'cmpl_Ischaemic_heart_disease', 'cmpl_Valvular_disease', 'cmpl_Cardiac_Disease_Other', 'cmpl_cirrhosis', 'cmpl_cirrhosisNO', 'cmpl_gall_bladder', 'cmpl_gi_bleed_var_source', 'cmpl_liver_disease', 'cmpl_liver_enzymes', 'cmpl_intestinal_obs', 'cmpl_GERD', 'cmpl_colonic', 'cmpl_gi_bleed_non_var_source', 'cmpl_pancreatitus', 'cmpl_peptic', 'cmpl_rectal', 'cmpl_hypertension', 'cmpl_kidneystones', 'cmpl_Acute_Kidney_Injury', 'cmpl_renal_failure', 'cmpl_Arthritis', 'cmpl_arthropathy', 'cmpl_abpa', 'cmpl_asthma', 'cmpl_bone_fracture', 'cmpl_depression', 'cmpl_hearing_loss', 'cmpl_ICU', 'cmpl_nasal_polyps', 'cmpl_osteopenia', 'cmpl_osteoporosis', 'cmpl_pneumothorax', 'cmpl_Port', 'cmpl_SinusDisease', 'cmpl_AbsVasDef', 'cmpl_other', 'cmpl_ChronicPseudomonas', 'cmpl_ChronicStaph', 'cult_no_growth', 'cult_normal_flora', 'cult_pseudo_aeruginosa', 'cult_other_psuedomonas', 'cult_pseudo_cepacia', 'cult_BCenocepacia', 'cult_BMultivorans', 'cult_BOtherBCepacia', 'cult_aspergillius', 'cult_specify', 'cult_staph', 'cult_alca', 'cult_ecoli', 'cult_hemo_influenza_b', 'cult_klebsiella', 'cult_MRSA', 'cult_Pandoria', 'cult_xanthomonas', 'cult_non_tuber_mycobact', 'DrugDornase', 'DrugTobramycin', 'DrugColistin', 'DrugMacrolidaAntibiotics', 'Drugibuprofen', 'DrugHypertonicsaline', 'oxygenTherapy', 'noninvVent', 'Intravenous (IV) Antibiotic Days in Hospital', 'Intravenous (IV) Antibiotic Days at Home', 'Non-IV Hospital Admission', 'Intravenous (IV) Antibiotic Numbers in Hospital', 'Intravenous (IV) Antibiotic Numbers at Home', 'Non-IV Hospital Admission Numbers', 'Pancreatic Enzyme Supplements', 'Cephalosporin', 'Coamoxiclav', 'CorticoCombo', 'CorticoInh', 'CorticoOral', 'Cotrimoxazole', 'Flucloxacillin', 'HDIbuprofen', 'HyperSaline', 'InhBroncho_BAAC', 'InhBroncho_LAAC', 'InhBroncho_LABA', 'InhBroncho_SAAC', 'InhBroncho_SABA', 'Ivacaftor', 'Macrolide', 'Mannitol', 'OralBroncho_BA', 'OralBroncho_THEOPH', 'Orkambi', 'TobramycinDry', 'acetylcysteine', 'antifungals', 'chronicMacrolide', 'chronicoral_amox', 'chronicoral_ceph', 'chronicoral_cotr', 'chronicoral_fluc', 'chronicoral_quin', 'chronicoral_tetra', 'colistimethate', 'colistin', 'dornaseAlfa', 'leukotrieneMod', 'promixin', 'tobiSolution', 'datadate', 'ageencounter']
2017
['ID', 'Gender', 'Genetic Mutation Allele 1', 'Genetic Mutation Allele 2', 's02genotypemut1specify', 's02genotypemut2specify', 'Height', 'Centile Height', 'Weight', 'Centile Weight', 'BMI', 's01encounterageyears', 's01encounteragemonths', 's03deathhaspatientdied', 's03deathcause', 'death_dt_anon', 'received_trans', 's10transplantdate', 'trans_lung_bilat', 'trans_lung_heart', 'trans_lung_lb_cadaveric', 's10transplantevaluation', 's10transplantevaluationoutcome', 's10transplantevaluationdate', 'FEV1', 'FEV1 Predicted', 'Best FEV1', 'Best FEV1 Predicted', 'smokeCigarettes', 'cmpl_diab_hgba1c_val', 'cmpl_hemoptysis', 'HemoptysisScanty', 'HemoptysisSevere', 'HemoptysisMassive', 'HemoptysisModerate', 'cmpl_CFRD', 'cmpl_diab_with_hyperglycemia', 'cmpl_other_glucose_ab', 'cfrd_treatment', 'cmpl_diab_gluc_intoler', 'cmpl_diab_dietary_chg', 'cmpl_oral_hypoglycemic_agnts', 'cmpl_diab_inter_insul', 'cmpl_microalbuminuria', 'cmpl_diabetes', 'cmpl_retinopathy', 'cmpl_cancer', 'cmpl_Arrhythmia', 'cmpl_Bradyarrythmia', 'cmpl_Tachyarrythmia', 'cmpl_Cough_Fracture', 'cmpl_Pulmonary_Abscess', 'cmpl_Cardiac_Disease', 'cmpl_Cardiac_Arrest', 'cmpl_Cardiomyopathy', 'cmpl_Congenital_heart_disease', 'cmpl_Heart_Failure', 'cmpl_Ischaemic_heart_disease', 'cmpl_Valvular_disease', 'cmpl_Cardiac_Disease_Other', 'cmpl_cirrhosis', 'cmpl_cirrhosisNO', 'cmpl_gall_bladder', 'cmpl_gi_bleed_var_source', 'cmpl_liver_disease', 'cmpl_liver_enzymes', 'cmpl_intestinal_obs', 'cmpl_GERD', 'cmpl_colonic', 'cmpl_gi_bleed_non_var_source', 'cmpl_pancreatitus', 'cmpl_peptic', 'cmpl_rectal', 'cmpl_hypertension', 'cmpl_kidneystones', 'cmpl_Acute_Kidney_Injury', 'cmpl_renal_failure', 'cmpl_Arthritis', 'cmpl_arthropathy', 'cmpl_abpa', 'cmpl_asthma', 'cmpl_bone_fracture', 'cmpl_depression', 'cmpl_hearing_loss', 'cmpl_ICU', 'cmpl_nasal_polyps', 'cmpl_osteopenia', 'cmpl_osteoporosis', 'cmpl_pneumothorax', 'cmpl_Port', 'cmpl_SinusDisease', 'cmpl_AbsVasDef', 'cmpl_other', 'cmpl_ChronicPseudomonas', 'cmpl_ChronicStaph', 'cult_no_growth', 'cult_normal_flora', 'cult_pseudo_aeruginosa', 'cult_other_psuedomonas', 'cult_pseudo_cepacia', 'cult_BCenocepacia', 'cult_BMultivorans', 'cult_BOtherBCepacia', 'cult_aspergillius', 'cult_specify', 'cult_staph', 'cult_alca', 'cult_ecoli', 'cult_hemo_influenza_b', 'cult_klebsiella', 'cult_MRSA', 'cult_Pandoria', 'cult_xanthomonas', 'cult_non_tuber_mycobact', 'DrugDornase', 'DrugTobramycin', 'DrugColistin', 'DrugMacrolidaAntibiotics', 'Drugibuprofen', 'DrugHypertonicsaline', 'oxygenTherapy', 'noninvVent', 'Intravenous (IV) Antibiotic Days in Hospital', 'Intravenous (IV) Antibiotic Days at Home', 'Non-IV Hospital Admission', 'Intravenous (IV) Antibiotic Numbers in Hospital', 'Intravenous (IV) Antibiotic Numbers at Home', 'Non-IV Hospital Admission Numbers', 'Pancreatic Enzyme Supplements', 'Cephalosporin', 'Coamoxiclav', 'CorticoCombo', 'CorticoInh', 'CorticoOral', 'Cotrimoxazole', 'Flucloxacillin', 'HDIbuprofen', 'HyperSaline', 'InhBroncho_BAAC', 'InhBroncho_LAAC', 'InhBroncho_LABA', 'InhBroncho_SAAC', 'InhBroncho_SABA', 'Ivacaftor', 'Macrolide', 'Mannitol', 'OralBroncho_BA', 'OralBroncho_THEOPH', 'Orkambi', 'TobramycinDry', 'acetylcysteine', 'antifungals', 'chronicMacrolide', 'chronicoral_amox', 'chronicoral_ceph', 'chronicoral_cotr', 'chronicoral_fluc', 'chronicoral_quin', 'chronicoral_tetra', 'colistimethate', 'colistin', 'dornaseAlfa', 'leukotrieneMod', 'promixin', 'tobiSolution', 'datadate', 'ageencounter']
2018
['ID', 'Gender', 'Genetic Mutation Allele 1', 'Genetic Mutation Allele 2', 's02genotypemut1specify', 's02genotypemut2specify', 'Height', 'Centile Height', 'Weight', 'Centile Weight', 'BMI', 's01encounterageyears', 's01encounteragemonths', 's03deathhaspatientdied', 's03deathcause', 'death_dt_anon', 'received_trans', 's10transplantdate', 'trans_lung_bilat', 'trans_lung_heart', 'trans_lung_lb_cadaveric', 's10transplantevaluation', 's10transplantevaluationoutcome', 's10transplantevaluationdate', 'FEV1', 'FEV1 Predicted', 'Best FEV1', 'Best FEV1 Predicted', 'smokeCigarettes', 'cmpl_diab_hgba1c_val', 'cmpl_hemoptysis', 'HemoptysisScanty', 'HemoptysisSevere', 'HemoptysisMassive', 'HemoptysisModerate', 'cmpl_CFRD', 'cmpl_diab_with_hyperglycemia', 'cmpl_other_glucose_ab', 'cfrd_treatment', 'cmpl_diab_gluc_intoler', 'cmpl_diab_dietary_chg', 'cmpl_oral_hypoglycemic_agnts', 'cmpl_diab_inter_insul', 'cmpl_microalbuminuria', 'cmpl_diabetes', 'cmpl_retinopathy', 'cmpl_cancer', 'cmpl_Arrhythmia', 'cmpl_Bradyarrythmia', 'cmpl_Tachyarrythmia', 'cmpl_Cough_Fracture', 'cmpl_Pulmonary_Abscess', 'cmpl_Cardiac_Disease', 'cmpl_Cardiac_Arrest', 'cmpl_Cardiomyopathy', 'cmpl_Congenital_heart_disease', 'cmpl_Heart_Failure', 'cmpl_Ischaemic_heart_disease', 'cmpl_Valvular_disease', 'cmpl_Cardiac_Disease_Other', 'cmpl_cirrhosis', 'cmpl_cirrhosisNO', 'cmpl_gall_bladder', 'cmpl_gi_bleed_var_source', 'cmpl_liver_disease', 'cmpl_liver_enzymes', 'cmpl_liver_disease_general', 'cmpl_intestinal_obs', 'cmpl_GERD', 'cmpl_colonic', 'cmpl_gi_bleed_non_var_source', 'cmpl_pancreatitus', 'cmpl_peptic', 'cmpl_rectal', 'cmpl_hypertension', 'cmpl_kidneystones', 'cmpl_Acute_Kidney_Injury', 'cmpl_renal_failure', 'cmpl_Arthritis', 'cmpl_arthropathy', 'cmpl_abpa', 'cmpl_asthma', 'cmpl_bone_fracture', 'cmpl_depression', 'cmpl_hearing_loss', 'cmpl_ICU', 'cmpl_nasal_polyps', 'cmpl_osteopenia', 'cmpl_osteoporosis', 'cmpl_pneumothorax', 'cmpl_Port', 'cmpl_SinusDisease', 'cmpl_AbsVasDef', 'cmpl_other', 'cmpl_ChronicPseudomonas', 'cmpl_ChronicStaph', 'cult_no_growth', 'cult_normal_flora', 'cult_pseudo_aeruginosa', 'cult_other_psuedomonas', 'cult_pseudo_cepacia', 'cult_BCenocepacia', 'cult_BMultivorans', 'cult_BOtherBCepacia', 'cult_aspergillius', 'cult_specify', 'cult_staph', 'cult_alca', 'cult_ecoli', 'cult_hemo_influenza_b', 'cult_klebsiella', 'cult_MRSA', 'cult_Pandoria', 'cult_xanthomonas', 'cult_non_tuber_mycobact', 'DrugDornase', 'DrugTobramycin', 'DrugColistin', 'DrugMacrolidaAntibiotics', 'Drugibuprofen', 'DrugHypertonicsaline', 'oxygenTherapy', 'noninvVent', 'Intravenous (IV) Antibiotic Days in Hospital', 'Intravenous (IV) Antibiotic Days at Home', 'Non-IV Hospital Admission', 'Intravenous (IV) Antibiotic Numbers in Hospital', 'Intravenous (IV) Antibiotic Numbers at Home', 'Non-IV Hospital Admission Numbers', 'Pancreatic Enzyme Supplements', 'Cephalosporin', 'Coamoxiclav', 'CorticoCombo', 'CorticoInh', 'CorticoOral', 'Cotrimoxazole', 'Flucloxacillin', 'HDIbuprofen', 'HyperSaline', 'InhBroncho_BAAC', 'InhBroncho_LAAC', 'InhBroncho_LABA', 'InhBroncho_SAAC', 'InhBroncho_SABA', 'Ivacaftor', 'Macrolide', 'Mannitol', 'OralBroncho_BA', 'OralBroncho_THEOPH', 'Orkambi', 'TobramycinDry', 'acetylcysteine', 'antifungals', 'chronicMacrolide', 'chronicoral_amox', 'chronicoral_ceph', 'chronicoral_cotr', 'chronicoral_fluc', 'chronicoral_quin', 'chronicoral_tetra', 'colistimethate', 'colistin', 'dornaseAlfa', 'leukotrieneMod', 'promixin', 'tobiSolution', 'datadate', 'ageencounter']

/var/folders/zq/v2r6yn111s3gpdf8lzf72xvw0000gn/T/ipykernel_45181/365697482.py:4: DtypeWarning:

Columns (5) have mixed types. Specify dtype option on import or set low_memory=False.