## Some individuals are much healthier for no reason looking at IVs

In [1]:
import data.breathe_data as bd
import models.builders as mb
import pandas as pd
import inference.long_inf_slicing as slicing
import inference.helpers as ih
from plotly.subplots import make_subplots
import src.cfr.cfr_helpers as cfrh

In [2]:
df = bd.load_meas_from_excel(
    "infer_all_19_data_with_best_FEV1",
    study_folder="CFR",
    str_cols_to_arrays=[
        "Airway resistance (%)",
        "P(HFEV1|FEF2575, bFEV1, FEV1)",
        "P(HFEV1|bFEV1, FEV1)",
        "P(HFEV1|FEV1)",
    ],
    use_csv=True,
    bypass_sanity_checks=True,
)

In [5]:
df.head(10)

,ID,Age,Height,best FEV1,Sex,Date Recorded,ecFEV1,ecFEF2575,ecFEF2575%ecFEV1,Predicted FEV1,...,"P(HFEV1|bFEV1, FEV1)",P(HFEV1|bFEV1),mean FEV1PersPred,mean FEV1PredFT,mean FEV1PredST,FEV1%PersPred,FEV1%PredFT,FEV1%PredST,pppFEV1 - ppFEV1ST,ppFEV1FT - ppFEV1ST
0,B162543,20,167,4.18,Female,2019-01-01,3.01,2.88,95.681067,3.525766,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,4.306868,4.323308,3.577866,69.888380,69.622612,84.128363,-14.239983,-14.505751
1,B163584,60,161,2.81,Female,2019-01-01,1.95,1.07,54.871796,2.446974,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 1.83881309e-311, 8.9...",[0.00000000e+000 0.00000000e+000 3.25226743e-3...,2.992444,2.982316,2.471380,65.164135,65.385438,78.903299,-13.739164,-13.517861
2,B158415,35,186,5.88,Male,2019-01-01,4.42,4.21,95.248868,4.819808,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,5.907549,5.909184,5.001867,74.819523,74.798818,88.367010,-13.547486,-13.568192
3,B160593,19,170,4.90,Male,2019-01-01,3.82,4.30,112.565452,4.175817,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,5.066170,5.100827,4.331774,75.402133,74.889809,88.185576,-12.783443,-13.295767
4,B158729,20,180,5.67,Male,2019-01-01,4.55,4.38,96.263735,4.779362,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,5.783340,5.788057,5.042917,78.674261,78.610143,90.225562,-11.551301,-11.615419
5,B164616,18,175,4.86,Male,2019-01-01,4.06,2.42,59.605914,4.393125,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,5.154843,5.118314,4.585510,78.760892,79.322988,88.539776,-9.778884,-9.216789
6,C222164,29,166,3.83,Female,2019-01-01,3.27,3.25,99.388380,3.373554,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,3.983322,3.998860,3.606458,82.092283,81.773305,90.670667,-8.578384,-8.897362
7,B158840,18,157,3.26,Female,2019-01-01,2.85,1.03,36.140351,3.085005,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,3.553542,3.481089,3.228313,80.201668,81.870923,88.281397,-8.079729,-6.410473
8,B161486,21,177,4.80,Male,2019-01-01,4.10,2.12,51.707315,4.622103,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,5.207162,5.141211,4.738092,78.737701,79.747744,86.532729,-7.795028,-6.784985
9,B162153,28,168,3.65,Female,2019-01-01,3.03,3.08,101.650163,3.475033,...,"[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...",[0.00000000e+000 0.00000000e+000 0.00000000e+0...,3.880895,3.915502,3.543936,78.074779,77.384712,85.498150,-7.423371,-8.113438

In [38]:
df.head(1)
df = df.reset_index()

In [ ]:
df[df.ID == id]

,ID,Age,Height,best FEV1,Sex,Date Recorded,ecFEV1,ecFEF2575,ecFEF2575%ecFEV1,Predicted FEV1,...,"P(HFEV1|bFEV1, FEV1)",P(HFEV1|bFEV1),mean FEV1PersPred,mean FEV1PredFT,mean FEV1PredST,FEV1%PersPred,FEV1%PredFT,FEV1%PredST,pppFEV1 - ppFEV1ST,ppFEV1FT - ppFEV1ST
2028,B162219,21,157,1.22,Female,2019-01-01,1.1,1.15,104.54545,3.089476,...,"[6.55227024e-15, 2.51117015e-11, 6.21388801e-0...",[1.66867424e-13 6.32765982e-11 4.69186013e-09 ...,2.32079,3.035319,3.035316,47.39766,36.240015,36.240045,11.157615,-0.00003

In [43]:
# Is P(HFEV1|FEV1, bFEV1, FEF25-75) correct?

id = "B162219"
dftmp = df[df.ID == id]
for i, row in dftmp.iterrows():
    res = cfrh.infer_hfev1_pers(row)

res

array([9.98984345e-13, 3.78311776e-09, 9.03716594e-07, 2.49802352e-05,
       1.55555314e-04, 4.21663252e-04, 7.52840449e-04, 1.15459760e-03,
       1.69755047e-03, 2.42588919e-03, 3.39239446e-03, 4.67914660e-03,
       6.38691583e-03, 8.62565003e-03, 1.15490665e-02, 1.53215017e-02,
       2.01936800e-02, 2.62943573e-02, 3.34612845e-02, 4.14183401e-02,
       4.91734895e-02, 5.56369369e-02, 6.09297644e-02, 6.37564803e-02,
       6.34308322e-02, 6.28682792e-02, 5.86990934e-02, 5.49157419e-02,
       4.92183835e-02, 4.33801022e-02, 3.72484409e-02, 3.25081058e-02,
       2.71192945e-02, 2.37536558e-02, 1.91807306e-02, 1.66829647e-02,
       1.39190691e-02, 1.14989882e-02, 1.03348921e-02, 8.85381096e-03,
       7.72136250e-03, 7.00799950e-03, 6.19246275e-03, 5.47033659e-03,
       4.92611278e-03, 4.38717152e-03, 3.87582198e-03, 3.41752210e-03,
       2.96931984e-03, 2.54835795e-03, 2.17609422e-03, 1.83917440e-03,
       1.51258129e-03, 1.21965845e-03, 9.77700424e-04, 7.64324579e-04,
       5.81640019e-04, 4.26937739e-04, 3.05361350e-04, 2.13698776e-04,
       1.45249621e-04, 9.58935500e-05, 6.19709955e-05, 3.91816253e-05,
       2.42106230e-05, 1.46374041e-05, 8.65870705e-06, 5.01084955e-06,
       2.83661885e-06, 1.57064847e-06, 8.50547519e-07, 4.50415674e-07,
       2.33226574e-07, 1.18072008e-07, 5.84353268e-08, 2.82695775e-08,
       1.33670211e-08, 6.17700614e-09, 2.78937276e-09, 1.23077219e-09,
       5.30578036e-10, 2.23449625e-10, 9.19236888e-11, 3.69361636e-11,
       1.44947959e-11, 5.55479740e-12, 2.07864501e-12, 7.59467084e-13,
       2.70903736e-13, 9.43321355e-14, 3.20630277e-14, 1.06368117e-14,
       3.44383780e-15, 1.08807968e-15, 3.35450406e-16, 1.00904069e-16,
       2.96118261e-17, 8.47737811e-18, 2.36734613e-18, 6.44807496e-19])

In [46]:
df[df.ID == id]['P(HFEV1|FEF2575, bFEV1, FEV1)']

2028    [9.98984345e-13, 3.78311776e-09, 9.03716594e-0...
Name: P(HFEV1|FEF2575, bFEV1, FEV1), dtype: object

In [5]:
df[['P(FEV1|M)', 'P(FEF2575%FEV1|M, FEV1)', 'P(bFEV1|M, FEV1, FEF2575%FEV1)', 'P(D|M)']] = df.apply(cfrh.get_p_data_under_model, axis=1)

In [6]:
df

,ID,Age,Height,best FEV1,Sex,Date Recorded,ecFEV1,ecFEF2575,ecFEF2575%ecFEV1,Predicted FEV1,...,mean FEV1PredST,FEV1%PersPred,FEV1%PredFT,FEV1%PredST,pppFEV1 - ppFEV1ST,ppFEV1FT - ppFEV1ST,P(FEV1|M),"P(FEF2575%FEV1|M, FEV1)","P(bFEV1|M, FEV1, FEF2575%FEV1)",P(D|M)
0,B162543,20,167,4.18,Female,2019-01-01,3.01,2.88,95.681067,3.525766,...,3.577866,69.888380,69.622612,84.128363,-14.239983,-14.505751,0.013659,3.305643e-02,0.000550,2.482374e-07
1,B163584,60,161,2.81,Female,2019-01-01,1.95,1.07,54.871796,2.446974,...,2.471380,65.164135,65.385438,78.903299,-13.739164,-13.517861,0.020184,1.185589e-02,0.004813,1.151779e-06
2,B158415,35,186,5.88,Male,2019-01-01,4.42,4.21,95.248868,4.819808,...,5.001867,74.819523,74.798818,88.367010,-13.547486,-13.568192,0.008132,3.346543e-02,0.000149,4.062874e-08
3,B160593,19,170,4.90,Male,2019-01-01,3.82,4.30,112.565452,4.175817,...,4.331774,75.402133,74.889809,88.185576,-12.783443,-13.295767,0.009760,2.845686e-02,0.000366,1.015787e-07
4,B158729,20,180,5.67,Male,2019-01-01,4.55,4.38,96.263735,4.779362,...,5.042917,78.674261,78.610143,90.225562,-11.551301,-11.615419,0.007003,3.412640e-02,0.000459,1.097886e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2032,B159700,18,161,2.35,Female,2019-01-01,2.02,3.46,171.287132,3.254105,...,3.199609,77.476591,62.820103,63.132715,14.343876,-0.312612,0.017346,1.090134e-05,0.012675,2.396802e-09
2033,B169105,37,164,1.69,Female,2019-01-01,1.37,1.71,124.817521,3.144692,...,3.086552,59.226901,44.381583,44.386101,14.840799,-0.004519,0.017999,1.214573e-04,0.023367,5.108203e-08
2034,B158151,18,156,1.84,Female,2019-01-01,1.64,2.42,147.560982,3.043475,...,2.990734,70.683433,54.818406,54.836045,15.847388,-0.017639,0.018574,5.488028e-05,0.022338,2.277033e-08
2035,B158720,30,153,1.66,Female,2019-01-01,1.57,2.56,163.057316,2.825143,...,2.775055,77.171752,56.562442,56.575462,20.596290,-0.013020,0.020016,9.924656e-06,0.025753,5.115890e-09
2036,B156254,45,181,1.93,Female,2019-01-01,1.93,4.33,224.352334,3.632932,...,3.559442,85.894617,54.221980,54.221980,31.672637,0.000000,0.015605,1.547379e-08,0.024463,5.906991e-12