In [1]:
import src.data.breathe_data as br
import plotly.express as px

In [14]:
df = br.load_meas_from_excel("BR_O2_FEV1_FEF2575_PEF_inferred_AR_IA").drop(columns=["AR", "IA"])

In [15]:
df.head()

,ID,Date Recorded,FEV1,O2 Saturation,FEF2575,PEF,ecFEV1,Age,Sex,Height,Predicted FEV1,Healthy O2 Saturation,ecFEV1 % Predicted,FEV1 % Predicted,O2 Saturation % Healthy,PEF (L/s),FEF2575%PEF,AR mean,IA mean
0,101,2021-05-25,1.68,98,1.17,227,1.69,53,Male,173.0,3.610061,97.150104,46.813611,46.536607,100.874827,3.783333,30.925110,47.601368,0.654616
1,101,2021-05-26,1.65,98,1.06,236,1.69,53,Male,173.0,3.610061,97.150104,46.813611,45.705597,100.874827,3.933333,26.949153,47.601368,0.654616
2,101,2021-05-27,1.69,98,1.12,183,1.69,53,Male,173.0,3.610061,97.150104,46.813611,46.813611,100.874827,3.050000,36.721311,47.601368,0.654616
3,101,2021-05-28,1.67,98,1.08,175,1.69,53,Male,173.0,3.610061,97.150104,46.813611,46.259604,100.874827,2.916667,37.028571,47.601368,0.654616
4,101,2021-05-29,1.69,98,1.16,171,1.76,53,Male,173.0,3.610061,97.150104,48.752636,46.813611,100.874827,2.850000,40.701754,44.593062,0.667227

## PEF, FEF2575 data quality

In [16]:
# Using plotly create histogram of fef2575%pef
fig = px.histogram(df, x="FEF2575%PEF")
fig.show()

In [17]:
# Why are there measurements > 100? even > 70?

# If the test is well performed, FEF2575 should never be > than PEF
# Or the PEF is super low
print(len(df[df["FEF2575%PEF"] > 70])/len(df)*100, "% are > 70%")

df[df["FEF2575%PEF"] > 100]

0.10411244143675169 % are > 70%

,ID,Date Recorded,FEV1,O2 Saturation,FEF2575,PEF,ecFEV1,Age,Sex,Height,Predicted FEV1,Healthy O2 Saturation,ecFEV1 % Predicted,FEV1 % Predicted,O2 Saturation % Healthy,PEF (L/s),FEF2575%PEF,AR mean,IA mean
8234,220,2023-05-05,1.74,100,6.92,406,1.79,41,Female,166.0,3.128822,98.096615,57.210025,55.611979,101.940317,6.766667,102.266010,36.675736,0.595679
10145,242,2021-06-28,3.17,98,3.87,213,3.17,39,Female,165.0,3.138644,98.114552,100.999034,100.999034,99.883247,3.550000,109.014085,7.592125,0.994936
10300,242,2022-06-20,2.66,99,2.52,73,2.66,39,Female,165.0,3.138644,98.114552,84.749978,84.749978,100.902463,1.216667,207.123288,15.247999,0.739259
10688,250,2022-07-21,4.57,98,5.28,260,4.57,37,Male,169.0,3.849069,97.221852,118.730020,118.730020,100.800384,4.333333,121.846154,3.910145,0.753682
10781,250,2023-03-08,4.21,97,4.75,201,4.26,37,Male,169.0,3.849069,97.221852,110.676124,109.377109,99.771808,3.350000,141.791045,5.160572,1.032076

In [18]:
# PEF should be greater than FEV1
idx = df[df["PEF (L/s)"] < df["FEV1"]].index
df[df["PEF (L/s)"] < df["FEV1"]]

,ID,Date Recorded,FEV1,O2 Saturation,FEF2575,PEF,ecFEV1,Age,Sex,Height,Predicted FEV1,Healthy O2 Saturation,ecFEV1 % Predicted,FEV1 % Predicted,O2 Saturation % Healthy,PEF (L/s),FEF2575%PEF,AR mean,IA mean
10300,242,2022-06-20,2.66,99,2.52,73,2.66,39,Female,165.0,3.138644,98.114552,84.749978,84.749978,100.902463,1.216667,207.123288,15.247999,0.739259
10688,250,2022-07-21,4.57,98,5.28,260,4.57,37,Male,169.0,3.849069,97.221852,118.730020,118.730020,100.800384,4.333333,121.846154,3.910145,0.753682
10781,250,2023-03-08,4.21,97,4.75,201,4.26,37,Male,169.0,3.849069,97.221852,110.676124,109.377109,99.771808,3.350000,141.791045,5.160572,1.032076
12145,272,2022-09-05,1.57,94,0.74,77,1.81,57,Female,165.0,2.663838,98.114552,67.947074,58.937518,95.806379,1.283333,57.662338,28.969152,4.082679

In [19]:
df1 = df.drop(idx, axis=0, inplace=False)

In [20]:
# FEF2575 should be lower than FEV1, otherwise:
# Test not well performed: PEF reached late -> flow increase over a long time (0.5s-0.1s) instead of 0.1s, little dynamic compression of the airways
df[df.FEV1 < df.FEF2575].sort_values(by="FEV1")

,ID,Date Recorded,FEV1,O2 Saturation,FEF2575,PEF,ecFEV1,Age,Sex,Height,Predicted FEV1,Healthy O2 Saturation,ecFEV1 % Predicted,FEV1 % Predicted,O2 Saturation % Healthy,PEF (L/s),FEF2575%PEF,AR mean,IA mean
10428,248,2022-10-11,0.78,98,0.93,170,1.06,44,Female,154.0,2.601447,98.311859,40.746559,29.983317,99.682786,2.833333,32.823529,55.443476,0.789030
10429,248,2023-08-01,1.06,98,1.07,201,1.06,44,Female,154.0,2.601447,98.311859,40.746559,40.746559,99.682786,3.350000,31.940299,55.443476,0.789030
6975,202,2021-10-29,1.23,82,1.99,217,1.85,64,Female,157.0,2.213968,98.258048,83.560392,55.556369,83.453724,3.616667,55.023041,16.609544,16.533523
9263,238,2022-12-28,1.25,98,2.99,300,1.28,59,Female,165.0,2.606672,98.114552,49.104751,47.953858,99.883247,5.000000,59.800000,45.968913,0.828017
932,102,2023-10-18,1.39,96,1.52,351,1.39,45,Male,176.0,3.987357,97.096293,34.860181,34.860181,98.870921,5.850000,25.982906,62.398152,0.905130
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1686,113,2021-07-26,5.10,98,5.12,502,5.27,26,Male,165.5,3.923640,97.284632,134.314070,129.981358,100.735335,8.366667,61.195219,2.315685,0.766121
1692,113,2021-09-06,5.12,98,5.14,393,5.12,26,Male,165.5,3.923640,97.284632,130.491089,130.491089,100.735335,6.550000,78.473282,2.569853,0.766121
1678,113,2021-06-16,5.13,98,5.36,508,5.13,26,Male,165.5,3.923640,97.284632,130.745954,130.745954,100.735335,8.466667,63.307087,2.569853,0.766121
1701,113,2021-12-13,5.25,98,5.33,585,5.25,26,Male,165.5,3.923640,97.284632,133.804339,133.804339,100.735335,9.750000,54.666667,2.315685,0.766121
1687,113,2021-08-02,5.27,99,5.30,493,5.27,26,Male,165.5,3.923640,97.284632,134.314070,134.314070,101.763247,8.216667,64.503043,2.315685,0.622701

# Modelling FEF2575

In [37]:
fig = px.scatter(df1, x="FEV1", y="FEF2575", color="ID")
fig.update_traces(marker=dict(size=3))
fig.update_layout(width=1400, height=1000)
fig.show()

In [30]:
fig = px.scatter(df1, x="PEF (L/s)", y="FEF2575", color="ID")
fig.update_traces(marker=dict(size=3))
# Update the layout to show othonormal axises
fig.update_layout(width=1000, height=600)
fig.show()

In [38]:
df1['FEF2575%FEV1'] = df1['FEF2575'] / df1['FEV1'] * 100

In [39]:
fig = px.scatter(df1, x="AR mean", y="FEF2575%FEV1", color="ID")
fig.update_traces(marker=dict(size=2))
fig.update_layout(width=1200, height=800)
fig.show()

In [40]:
fig = px.scatter(df1, x="AR mean", y="FEF2575%PEF", color="ID")
fig.update_traces(marker=dict(size=2))
fig.update_layout(width=1200, height=800)
fig.show()

In [43]:
fig = px.scatter(df1, x="IA mean", y="FEF2575%PEF", color="ID")
fig.update_traces(marker=dict(size=2))
fig.update_layout(width=1200, height=800)
fig.show()

In [44]:
fig = px.scatter(df1, x="IA mean", y="FEV1", color="ID")
fig.update_traces(marker=dict(size=2))
fig.update_layout(width=1200, height=800)
fig.show()